correo_proveedor = "eliaslashero@gmail.com"
modo_guardado = "Mediante descarga"
default_template = r"C:\Users\palvaroh\Desktop\plantilla.docx"
output_folder = r"C:\Users\palvaroh\Desktop"
nombre = "Pablo"
